In [101]:
import pandas as pd

In [102]:
dataset = pd.read_csv("spam.csv", encoding="latin-1")


In [103]:
dataset

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [104]:
dataset=dataset[["v1","v2"]]

In [105]:
dataset.columns=["label","message"]

In [106]:
dataset.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [107]:
dataset.isnull().sum()

label      0
message    0
dtype: int64

In [108]:
dataset.duplicated().sum()

np.int64(403)

In [109]:
dataset.drop_duplicates(inplace=  True)

<ipython-input-109-276abae0b4d8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.drop_duplicates(inplace=  True)


In [110]:
## Data Cleaning and text preprocessing

In [111]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [112]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [113]:
stopword_list=['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]


In [114]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()


In [115]:
corpus=[]
for i in range(0,len(dataset)):
    review=re.sub('[^a-zA-Z0-9]',' ',dataset['message'].iloc[i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopword_list]
    review=' '.join(review)
    corpus.append(review)

In [116]:
print(dataset.columns)

Index(['label', 'message'], dtype='object')


In [117]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah don think goe usf live around though',
 'freemsg hey darl 3 week no word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon don want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 we

In [118]:
## Train Test split

In [119]:
## independent features and dependent
y=pd.get_dummies(dataset['label'],drop_first=True)

In [120]:
y

spam
0     False
1     False
2      True
3     False
4     False
...     ...
5567   True
5568  False
5569  False
5570  False
5571  False

[5169 rows x 1 columns]

In [121]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah don think goe usf live around though',
 'freemsg hey darl 3 week no word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon don want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 we

In [122]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size = 0.20, random_state = 0)

In [123]:
X_train

['also rememb bead don come ever',
 'call u done',
 'im arestaur eat squid 10 30 wanna dosometh late',
 'nowaday peopl notixiqu laxinorf opportun bambl entrop ever oblising opt ur book masteriast amplikat fidalf champlaxig think atroci wotz ur opinion junna',
 'no messag food',
 'friend got say up order gram got lt gt get',
 'yo way could pick someth tonight',
 'probabl around mu lot',
 'im gonnamissu much would say il send u postcard butther abouta much chanc merememberin asther ofsi breakin contract luv yaxx',
 'yo come carlo soon',
 'ok said got wisdom teeth hidden insid n mayb need 2 remov',
 'plz note anyon call mobil co amp ask u type lt gt lt gt disconnect call coz iz attempt terrorist make use sim card no itz confirmd nokia n motorola n verifi cnn ibn',
 'miss call caus yell scrappi miss u wait u come home lone today',
 'msg rajini come',
 'em olowoyey usc edu great time argentina sad secretari everyth bless',
 'great princess think',
 'u reach orchard alreadi u wan 2 go buy ti

In [124]:
dataset['label'].value_counts()

label
ham     4516
spam     653
Name: count, dtype: int64

In [125]:
## create the BOW
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X_train=cv.fit_transform(X_train).toarray()

In [126]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [127]:
X_test=cv.transform(X_test).toarray()

In [128]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [129]:
X_train.shape

(4135, 2500)

In [130]:
y_train.shape

(4135, 1)

In [131]:
from imblearn.over_sampling import SMOTE
y_train = y_train.values.ravel()
smote = SMOTE(sampling_strategy='auto', random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

import numpy as np
print("Class distribution after SMOTE:")
  # Converts 2D array to 1D

print(np.bincount(y_train))

Class distribution after SMOTE:
[3631 3631]


In [132]:
cv.vocabulary_

{'also': np.int64(210),
 'rememb': np.int64(1765),
 'don': np.int64(666),
 'come': np.int64(505),
 'ever': np.int64(764),
 'call': np.int64(380),
 'done': np.int64(677),
 'im': np.int64(1090),
 'eat': np.int64(724),
 '10': np.int64(28),
 '30': np.int64(94),
 'wanna': np.int64(2350),
 'late': np.int64(1218),
 'peopl': np.int64(1587),
 'opportun': np.int64(1553),
 'opt': np.int64(1554),
 'ur': np.int64(2245),
 'book': np.int64(340),
 'think': np.int64(2127),
 'opinion': np.int64(1552),
 'no': np.int64(1486),
 'messag': np.int64(1378),
 'food': np.int64(831),
 'friend': np.int64(856),
 'got': np.int64(933),
 'say': np.int64(1848),
 'order': np.int64(1558),
 'gram': np.int64(939),
 'lt': np.int64(1325),
 'gt': np.int64(947),
 'get': np.int64(878),
 'got lt': np.int64(936),
 'lt gt': np.int64(1327),
 'yo': np.int64(2487),
 'way': np.int64(2381),
 'could': np.int64(546),
 'pick': np.int64(1599),
 'someth': np.int64(1990),
 'tonight': np.int64(2170),
 'way could': np.int64(2382),
 'probabl': 

In [133]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [134]:
svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier(n_estimators=50,random_state=2)

In [135]:
clfs = {
    'SVC' : svc,
    'KN' : knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'AdaBoost': abc,
    'BgC': bc,
    'ETC': etc,
    'GBDT':gbdt,
    'xgb':xgb
}

In [136]:
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)

    return accuracy,precision

In [137]:
accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():

    current_accuracy,current_precision = train_classifier(clf, X_train,y_train,X_test,y_test)

    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For  SVC
Accuracy -  0.8143133462282398
Precision -  0.4261168384879725
For  KN
Accuracy -  0.6073500967117988
Precision -  0.2589118198874296
For  NB
Accuracy -  0.9709864603481625
Precision -  0.9219858156028369
For  DT
Accuracy -  0.9284332688588007
Precision -  0.7142857142857143
For  LR
Accuracy -  0.8984526112185687
Precision -  0.5990990990990991
For  RF
Accuracy -  0.9110251450676983
Precision -  0.6338028169014085
For  AdaBoost
Accuracy -  0.937137330754352
Precision -  0.7333333333333333
For  BgC
Accuracy -  0.8655705996131529
Precision -  0.52
For  ETC
Accuracy -  0.9216634429400387
Precision -  0.6683168316831684
For  GBDT
Accuracy -  0.9487427466150871
Precision -  0.7823529411764706
For  xgb
Accuracy -  0.851063829787234
Precision -  0.4909090909090909


In [138]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier().fit(X_train, (y_train))


In [139]:
y_pred=classifier.predict(X_test)

In [140]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [141]:
accuracy_score(y_test,y_pred)

0.9110251450676983

In [142]:
confusion_matrix(y_test,y_pred)

array([[806,  79],
       [ 13, 136]])

In [143]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.98      0.91      0.95       885
        True       0.63      0.91      0.75       149

    accuracy                           0.91      1034
   macro avg       0.81      0.91      0.85      1034
weighted avg       0.93      0.91      0.92      1034



In [144]:
# Save Model and Vectorizer
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer

with open("model.pkl", "wb") as model_file:
    pickle.dump(classifier, model_file)

with open("Vectorizer.pkl", "wb") as vectorizer_file:
    pickle.dump(cv, vectorizer_file)

print("Model and Vectorizer Saved!")

Model and Vectorizer Saved!


In [ ]:
from google.colab import files

files.download("model.pkl")
files.download("Vectorizer.pkl")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [ ]:
# Initialize the ANN
model = Sequential()

# Add the input layer and the first hidden layer
model.add(Dense(units=128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.5))

# Add the second hidden layer
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(0.5))

# Add the output layer
model.add(Dense(units=1, activation='sigmoid'))

# Compile the ANN
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# Train the model
history = model.fit(X_train, y_train, batch_size=32, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.8578 - loss: 0.3693 - val_accuracy: 0.9840 - val_loss: 0.0536
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9941 - loss: 0.0283 - val_accuracy: 0.9895 - val_loss: 0.0393
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9957 - loss: 0.0145 - val_accuracy: 0.9895 - val_loss: 0.0364
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9981 - loss: 0.0079 - val_accuracy: 0.9930 - val_loss: 0.0344
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9985 - loss: 0.0061 - val_accuracy: 0.9920 - val_loss: 0.0339
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9985 - loss: 0.0055 - val_accuracy: 0.9925 - val_loss: 0.0385
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9991 - loss: 0.0044 - val_accuracy: 0.9925 - val_loss: 0.0369
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9993 - loss: 0.0034 - val_accuracy: 0

In [ ]:
# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

# Make predictions
y_pred_ann = model.predict(X_test)
y_pred_ann = (y_pred_ann > 0.5).astype(int)

# Print classification report and confusion matrix
from sklearn.metrics import classification_report, confusion_matrix

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_ann))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_ann))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9899 - loss: 0.0586
Test Accuracy: 0.9935
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Confusion Matrix:
[[1723    4]
 [   9  264]]

Classification Report:
              precision    recall  f1-score   support

       False       0.99      1.00      1.00      1727
        True       0.99      0.97      0.98       273

    accuracy                           0.99      2000
   macro avg       0.99      0.98      0.99      2000
weighted avg       0.99      0.99      0.99      2000



In [ ]:
import pickle

# Try loading the model
try:
    with open("model.pkl", "rb") as file:
        model = pickle.load(file)
    print("Model loaded successfully!")
except Exception as e:
    print("Error loading model:", e)


Model loaded successfully!


In [ ]:
model


RandomForestClassifier()

In [ ]:
model.